-- ============================================================================
--  kajiji Portfolio — Supabase (PostgreSQL) schema
--
--  HOW TO RUN:
--    Supabase Dashboard → SQL Editor → New query → paste this file → Run.
--
--  This file replaces the legacy MySQL `database.sql` (which is kept in the
--  repository only for reference / data migration). It is safe to re-run:
--  tables use IF NOT EXISTS and seed rows use ON CONFLICT DO NOTHING.
--
--  NOTE: intentionally NO "CREATE DATABASE" / "USE" statements — the Supabase
--  project already provides the PostgreSQL database (name: postgres).
-- ============================================================================

BEGIN;

-- ────────────────────────────────────────────────────────────────────────────
-- 1. messages — contact form submissions
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS messages (
  id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(100) NOT NULL,
  email      VARCHAR(150) NOT NULL,
  subject    VARCHAR(200),
  message    TEXT         NOT NULL,
  created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  is_read    BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_is_read    ON messages (is_read);

-- ────────────────────────────────────────────────────────────────────────────
-- 2. admins — admin panel accounts
--    Default login: admin / admin123
--    The hash below is a PHP bcrypt hash generated with:
--      password_hash('admin123', PASSWORD_DEFAULT)
--    Plain-text passwords are NEVER stored. Log in via /admin/login.php,
--    which uses password_verify(). To change the password, generate a new
--    hash with:  php -r "echo password_hash('new-password', PASSWORD_DEFAULT);"
--    and UPDATE the admins table with it.
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS admins (
  id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      VARCHAR(50)  UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- Seed admin (same credentials as the old MySQL database: admin / admin123).
INSERT INTO admins (username, password_hash)
VALUES ('admin', '$2y$10$bk.DJn8wmfcGyJ3lYmUY8.19WBv7ejfNueWpqEooBvYQeomiR/VPu')
ON CONFLICT (username) DO NOTHING;

-- ────────────────────────────────────────────────────────────────────────────
-- 3. projects — portfolio projects (same seed data as the MySQL database)
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS projects (
  id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug             VARCHAR(50)  UNIQUE NOT NULL,
  title            VARCHAR(100) NOT NULL,
  tagline          VARCHAR(200),
  description      TEXT,
  hero_image_url   VARCHAR(500),
  youtube_video_id VARCHAR(50),
  tech_stack       VARCHAR(255),
  created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- Seed projects (unchanged from the original MySQL seed data).
INSERT INTO projects (slug, title, tagline, description, hero_image_url, youtube_video_id, tech_stack) VALUES
('taskflow', 'TaskFlow', 'A lightweight productivity app', 'A task manager with drag-and-drop, offline saving, and reminders.', 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&w=1200&q=80', 'dQw4w9WgXcQ', 'HTML,CSS,JavaScript,LocalStorage'),
('weatherscope', 'WeatherScope', 'Real-time weather dashboard', 'A dashboard showing current weather + 7-day forecast for any city.', 'https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?auto=format&fit=crop&w=1200&q=80', 'dQw4w9WgXcQ', 'JavaScript,REST API,Chart.js,CSS Grid'),
('codecollab', 'CodeCollab', 'Collaborative code editor', 'Multi-user real-time code editor with shared rooms.', 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80', 'dQw4w9WgXcQ', 'React,Node.js,Socket.io,Monaco')
ON CONFLICT (slug) DO NOTHING;

COMMIT;

-- ============================================================================
-- 4. Row Level Security (RLS)
--
-- RLS is ENABLED on every table with NO public policies. This is deliberate:
--   * Supabase auto-exposes every table through its REST/PostgREST API to the
--     anonymous ("anon") and "authenticated" roles. With RLS enabled and no
--     policies, those API roles are DENIED all access by default — the tables
--     cannot be read or written through the public API.
--   * The PHP application connects SERVER-SIDE with the postgres (SQL) role
--     over the direct/pooled PostgreSQL connection. That connection is not
--     subject to these RLS policies, so the website keeps full access.
--
-- Do NOT add "USING (true)" style allow-all policies just to make the public
-- API work — the PHP backend is the only intended database client.
-- (The service_role key must never be embedded in browser code; this project
--  does not use the Supabase JS/REST API at all.)
-- ============================================================================

ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE admins   ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

-- The Vite client uses the publishable anon key. Projects are public, while
-- contact submissions are insert-only for visitors. Admin message management
-- should be protected with Supabase Auth or a server-side edge function; the
-- frontend never receives a service-role key.
DROP POLICY IF EXISTS "Public can read projects" ON projects;
CREATE POLICY "Public can read projects"
  ON projects FOR SELECT
  TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS "Public can submit messages" ON messages;
CREATE POLICY "Public can submit messages"
  ON messages FOR INSERT
  TO anon, authenticated
  WITH CHECK (
    char_length(name) BETWEEN 2 AND 100
    AND char_length(email) BETWEEN 3 AND 150
    AND char_length(message) BETWEEN 10 AND 5000
    AND (subject IS NULL OR char_length(subject) <= 200)
  );
